import Navbar from './Navbar'
import { Footer } from './Footer'
import { ReactNode, useState } from 'react';
import styles from '@/styles/Home.module.css'
import Head from 'next/head';
import Sidebar from './Sidebar'

type LayoutProps = {
  children: ReactNode;
  idioma: string;
  setIdioma: React.Dispatch<React.SetStateAction<string>>;
  darkMode: string;
  setDarkMode: React.Dispatch<React.SetStateAction<string>>;
}

export default function Layout({ children, idioma, setIdioma, darkMode, setDarkMode }: LayoutProps) {
  const [isOpen, setIsOpen] = useState(false)

  const toggleSidebar = () => {
    setIsOpen(!isOpen)
  }
  return (
    <>
      <Head>
        <title>Juan Saugar - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar idioma={idioma} setIdioma={setIdioma} darkMode={darkMode} setDarkMode={setDarkMode} toggleSidebar={toggleSidebar} />
      <Sidebar isOpen={isOpen} toggleSidebar={toggleSidebar} />
      <main className={darkMode === "dark" ? styles["main-dark"] : styles["main-light"]}>
        <div className={styles.div}>
          {children}
        </div>
      </main>
      <Footer darkMode={darkMode} />
    </>
  )
}